services:
  postgres:
    image: postgres:16
    container_name: postgres-db

    environment:
      POSTGRES_USER: user
      POSTGRES_PASSWORD: password
      POSTGRES_DB: mydb

    ports:
      - "5432:5432"

    volumes:
      - user-service-postgres-data:/var/lib/postgresql/data

volumes:
  user-service-postgres-data: