services:
  postgres:
    image: postgres:16
    container_name: postgres-db

    environment:
      POSTGRES_USER: user
      POSTGRES_PASSWORD: password
      POSTGRES_DB: mydb

    ports:
      - "5432:5432"

    volumes:
      - user-service-postgres-data:/var/lib/postgresql/data

  search-core:
    build:
      context: ..
      dockerfile: services/search-core/Dockerfile
    container_name: search-core

    ports:
      - "8081:8081"
      - "8082:8082"

    volumes:
      # Go gateway writes dictionary.txt into its own working directory on the host;
      # mounting that same directory here is how search-core gets access to it
      # without the two services needing to talk to each other directly (yet).
      - ../services/gateway:/data

volumes:
  user-service-postgres-data: