// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.36.11
// 	protoc        v5.29.3
// source: keywords/search.proto

package keywordspb

import (
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	reflect "reflect"
	sync "sync"
	unsafe "unsafe"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

type SearchRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Query         string                 `protobuf:"bytes,1,opt,name=query,proto3" json:"query,omitempty"`
	Limit         int32                  `protobuf:"varint,2,opt,name=limit,proto3" json:"limit,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *SearchRequest) Reset() {
	*x = SearchRequest{}
	mi := &file_keywords_search_proto_msgTypes[0]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *SearchRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*SearchRequest) ProtoMessage() {}

func (x *SearchRequest) ProtoReflect() protoreflect.Message {
	mi := &file_keywords_search_proto_msgTypes[0]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use SearchRequest.ProtoReflect.Descriptor instead.
func (*SearchRequest) Descriptor() ([]byte, []int) {
	return file_keywords_search_proto_rawDescGZIP(), []int{0}
}

func (x *SearchRequest) GetQuery() string {
	if x != nil {
		return x.Query
	}
	return ""
}

func (x *SearchRequest) GetLimit() int32 {
	if x != nil {
		return x.Limit
	}
	return 0
}

type SearchResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Results       []string               `protobuf:"bytes,1,rep,name=results,proto3" json:"results,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *SearchResponse) Reset() {
	*x = SearchResponse{}
	mi := &file_keywords_search_proto_msgTypes[1]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *SearchResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*SearchResponse) ProtoMessage() {}

func (x *SearchResponse) ProtoReflect() protoreflect.Message {
	mi := &file_keywords_search_proto_msgTypes[1]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use SearchResponse.ProtoReflect.Descriptor instead.
func (*SearchResponse) Descriptor() ([]byte, []int) {
	return file_keywords_search_proto_rawDescGZIP(), []int{1}
}

func (x *SearchResponse) GetResults() []string {
	if x != nil {
		return x.Results
	}
	return nil
}

var File_keywords_search_proto protoreflect.FileDescriptor

const file_keywords_search_proto_rawDesc = "" +
	"\n" +
	"\x15keywords/search.proto\x12\fkeywords.api\";\n" +
	"\rSearchRequest\x12\x14\n" +
	"\x05query\x18\x01 \x01(\tR\x05query\x12\x14\n" +
	"\x05limit\x18\x02 \x01(\x05R\x05limit\"*\n" +
	"\x0eSearchResponse\x12\x18\n" +
	"\aresults\x18\x01 \x03(\tR\aresults2V\n" +
	"\rSearchService\x12E\n" +
	"\x06Search\x12\x1b.keywords.api.SearchRequest\x1a\x1c.keywords.api.SearchResponse\"\x00BiZggithub.com/rwrwdss/microservices-cache-app/services/gateway/internal/searchclient/keywordspb;keywordspbb\x06proto3"

var (
	file_keywords_search_proto_rawDescOnce sync.Once
	file_keywords_search_proto_rawDescData []byte
)

func file_keywords_search_proto_rawDescGZIP() []byte {
	file_keywords_search_proto_rawDescOnce.Do(func() {
		file_keywords_search_proto_rawDescData = protoimpl.X.CompressGZIP(unsafe.Slice(unsafe.StringData(file_keywords_search_proto_rawDesc), len(file_keywords_search_proto_rawDesc)))
	})
	return file_keywords_search_proto_rawDescData
}

var file_keywords_search_proto_msgTypes = make([]protoimpl.MessageInfo, 2)
var file_keywords_search_proto_goTypes = []any{
	(*SearchRequest)(nil),  // 0: keywords.api.SearchRequest
	(*SearchResponse)(nil), // 1: keywords.api.SearchResponse
}
var file_keywords_search_proto_depIdxs = []int32{
	0, // 0: keywords.api.SearchService.Search:input_type -> keywords.api.SearchRequest
	1, // 1: keywords.api.SearchService.Search:output_type -> keywords.api.SearchResponse
	1, // [1:2] is the sub-list for method output_type
	0, // [0:1] is the sub-list for method input_type
	0, // [0:0] is the sub-list for extension type_name
	0, // [0:0] is the sub-list for extension extendee
	0, // [0:0] is the sub-list for field type_name
}

func init() { file_keywords_search_proto_init() }
func file_keywords_search_proto_init() {
	if File_keywords_search_proto != nil {
		return
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: unsafe.Slice(unsafe.StringData(file_keywords_search_proto_rawDesc), len(file_keywords_search_proto_rawDesc)),
			NumEnums:      0,
			NumMessages:   2,
			NumExtensions: 0,
			NumServices:   1,
		},
		GoTypes:           file_keywords_search_proto_goTypes,
		DependencyIndexes: file_keywords_search_proto_depIdxs,
		MessageInfos:      file_keywords_search_proto_msgTypes,
	}.Build()
	File_keywords_search_proto = out.File
	file_keywords_search_proto_goTypes = nil
	file_keywords_search_proto_depIdxs = nil
}
